export const kompaktDefaults = {
  page: {
    widthMm: 210,
    heightMm: 297,
    marginTopMm: 13,
    marginRightMm: 13,
    marginBottomMm: 12,
    marginLeftMm: 13,
  },
  layout: {
    headerHeightMm: 22,
    contentTopMm: 31,
    headerToContentGapMm: 9,
    footerClearanceMm: 15,
    leftColumnWidthMm: 108,
    columnGapMm: 10,
    rightColumnWidthMm: 66,
    sectionGapMm: 3.5,
    entryGapMm: 3.2,
    sectionTitleGapMm: 3,
    entryContentGapMm: 0.7,
  },
  colors: {
    primary: "#073D96",
    accent: "#FF6200",
    text: "#3F494F",
    muted: "#6D757A",
    divider: "#AEB6BA",
    pattern: "#FFD7BC",
    inactive: "#E1E5E7",
  },
} as const;
